journal.bestiary.regional.title=區域敵人
journal.bestiary.bosses.title=頭目及其手下
journal.bestiary.universal.title=全局敵人
journal.bestiary.rare.title=稀有敵人
journal.bestiary.quest.title=任務相關敵人
journal.bestiary.neutral.title=中立角色
journal.bestiary.ally.title=盟友
journal.bestiary.trap.title=陷阱
journal.bestiary.plant.title=植物

journal.catalog.melee_weapons.title=近戰武器
journal.catalog.armor.title=護甲
journal.catalog.enchantments.title=附魔
journal.catalog.glyphs.title=刻印
journal.catalog.thrown_weapons.title=投擲武器
journal.catalog.wands.title=法杖
journal.catalog.rings.title=戒指
journal.catalog.artifacts.title=神器
journal.catalog.trinkets.title=飾品
journal.catalog.misc_equipment.title=雜項裝備

journal.catalog.potions.title=藥水
journal.catalog.scrolls.title=卷軸
journal.catalog.seeds.title=種子
journal.catalog.stones.title=符石
journal.catalog.food.title=食物
journal.catalog.exotic_potions.title=合劑
journal.catalog.exotic_scrolls.title=秘卷
journal.catalog.bombs.title=炸彈
journal.catalog.tipped_darts.title=塗藥飛鏢
journal.catalog.brews_elixirs.title=魔藥與秘藥
journal.catalog.spells.title=法術
journal.catalog.misc_consumables.title=雜項消耗品


journal.document.adventurers_guide.title=地城探索指南
journal.document.adventurers_guide.intro.title=基礎介紹
journal.document.adventurers_guide.intro.body=歡迎，冒險家，你正在閱讀地城探索指南。本手冊包含著能幫助新手冒險家存活並精進能力的所有提示與技巧!\n\n本手冊做為參考用的魔法指南，它會在適當的時機讓你知道你應該讀哪個部分以解決當前情況。\n\n(當右上方日誌鈕發亮時，就代表著指南有事要告訴你! 有些頁面鬆脫了，可能散落在地下城中?)
journal.document.adventurers_guide.examining.title=審視周遭
journal.document.adventurers_guide.examining.body=想都不想就衝進去和敵人作戰絕對不是最好的做法。在戰鬥前最好先觀察敵人以及周遭環境，並找出與其抗衡的方法! 看到新東西時最好都 “查看” 一下!\n\n"查看" 任何東西都是一瞬間的行動，不消耗任何時間，所以最好養成遇到新事物就檢查看看的習慣。\n\n(按下放大鏡按鈕再點擊想要檢驗的東西就能查看。也可以點擊狀態效果來查看它們。)
journal.document.adventurers_guide.surprise_attacks.title=伏擊
journal.document.adventurers_guide.surprise_attacks.body=伏擊是一種必定命中，對蛇和怨靈等善於閃躲的敵人特別有用的攻擊。\n\n你可以在敵人正在通過門時以及發覺你前，又或者試圖跑出敵人可視範圍外進行攻擊以做出伏擊。
journal.document.adventurers_guide.identifying.title=鑑定物品
journal.document.adventurers_guide.identifying.body=藥水的顏色以及卷軸上的符號等會隨著地下城而有所變動。如果夠幸運的話，未鑑定的裝備可能是升級過或帶有附魔效果的良品，但更有可能受到詛咒!\n\n鑑定、升級以及去邪卷軸等道具可以大幅降低使用未鑑定裝備的風險。\n\n(你可以在你的日誌中找到你已經鑑定過的所有物品。)
journal.document.adventurers_guide.food.title=與飢餓共舞
journal.document.adventurers_guide.food.body=有效分配糧食能大幅提高存活的機率。除非極度飢餓，否則不吃東西也不會怎麼樣!\n\n非極度飢餓時，生命值會緩慢恢復。在滿血時進食，就會白白浪費掉此恢復效果。\n\n如果你跟據你當下的生命值來合理進食，糧食就不會這麼快吃完。
journal.document.adventurers_guide.alchemy.title=煉金與飾品
journal.document.adventurers_guide.alchemy.body=如果你覺得某些消耗品沒什麼用，你可以將其作為材料使用! 道具可以用於特定的配方或轉化成有更多用途的煉金能量。將藥水及卷軸轉化成能量也能鑑定它們!\n\n飾品是透過煉金術製造，升級的裝備。它們能提供各式各樣的幫助，只需要一些能量以及魔法催化物來製作。\n\n(你可以在第3~4層樓找到第一個煉金釜，也可以在鍋子附近找到煉金配方書的殘頁。)
journal.document.adventurers_guide.dieing.title=直視失敗
journal.document.adventurers_guide.dieing.body=探索地下城這種工作極其危險，而大多數冒險家最終都將於此喪命。\n\n好運能增加成功的機率，但最優秀的冒險家都懂得利用各種小技巧來提高他們成功的機會。\n\n(就算一直死也不要太灰心，這個遊戲並沒有那麼容易! 不要只想著怎麼獲勝，學習這個遊的機制並慢慢進步更重要。)
journal.document.adventurers_guide.searching.title=搜尋周邊
journal.document.adventurers_guide.searching.body=地下城裡頭有許多隱藏的門以及陷阱，第一眼看過去可能不太明顯。如果周遭看起來不太對勁，可以花點時間仔細搜尋陷阱與隠藏門。\n\n(按兩下放大鏡按鈕就可以進行搜尋。也許在你找到這一頁的附近就有隱藏門也說不定!)
journal.document.adventurers_guide.strength.title=力量機制
journal.document.adventurers_guide.strength.body=在這裡你沒有時間通過訓練來掌握找到的新武器和護甲，只能依靠自身的體力才能有效的使用它們。 \n\n力量藥劑及升級卷軸是最有效的方式，使你能夠使用更高力量需求值的高階裝備。\n\n多數成功的冒險家依賴高階裝備，但也別忽略很快就能用的裝備。
journal.document.adventurers_guide.upgrades.title=強化裝備
journal.document.adventurers_guide.upgrades.body=越是往地下城的深處走，就越需要透過魔法升級高階裝備。但也需要與之相稱的力量才能正常使用。\n\n法杖、戒指以及神器不需要力量即可裝備，但通常有限制使用次數，或不能直接對戰鬥有所幫助。\n\n好好決定要升級的道具才能活過前期並為後面的旅途做好準備。
journal.document.adventurers_guide.looting.title=搜刮技巧
journal.document.adventurers_guide.looting.body=某些房間裡面的物品會比其他的高級許多。這種房間通常門會被鎖上、有障礙物擋著，或有其它守衛護著物品。在同一層樓中通常有物品能突破守衛或障礙。\n\n力量藥水以及升級卷軸都是對探索度的優良指標。每五層樓都能找到兩罐力量藥水以及三張升級卷軸。\n\n(你可以在日誌的"筆記"部分找到重要地標以及尚未使用的鑰匙。)
journal.document.adventurers_guide.levelling.title=經驗獲取
journal.document.adventurers_guide.levelling.body=你升級時，命中率、閃避率及生命值都會增加，同時也會讓你獲得一點天賦點。這些都能對戰局有巨大的影響。探索時最好每往下一層就升一級。\n\n也許不探索、迴避戰鬥並直接往最深處衝聽起來是個好辦法，但最後只會讓你的資源及經驗極度匱乏。\n\n(你可以在遊戲介面的角落看到你的英雄狀態，包含經驗值。點擊英雄的肖像就可以查看更多相關資訊。)
journal.document.adventurers_guide.positioning.title=擇地而戰
journal.document.adventurers_guide.positioning.body=策略與裝備同等重要，在自己狀況不佳時，比如被敵人包圍等，都可以透過較好的站位來避免。\n\n舉例來說，多數地下城都有狹窄的走廊，可以用來使自己一次只需對付一位敵人。這樣的走廊通常也會有門能用來伏擊!\n\n大多數的環境也都有可以讓你利用的特點，比如草叢、水坑、深淵或是陷阱。
journal.document.adventurers_guide.magic.title=魔法攻擊
journal.document.adventurers_guide.magic.body=魔法攻擊能夠無視目標的防禦，且難以閃避。這表示法杖的傷害能力會非常可靠，但也導致能使用魔法攻擊的敵人極具威脅性!\n\n但魔法攻擊也不是沒有缺點。法杖都有充能次數限制，且大多數敵人沒有辦法在近身戰時用魔法攻擊。\n\n面對懂使用魔法的敵人時，要懂得如何才能讓牠們不能對你使用魔法攻擊。

journal.document.alchemy_guide.title=鍊金指南
journal.document.alchemy_guide.potions.title=引言與藥劑釀造
journal.document.alchemy_guide.potions.body=歡迎來到《鍊金術的實際應用》! 這是業餘鍊金愛好者和冒險家們的鍊金配方參考書。\n\n我們將從最經典的配方開始: 藥劑!\n\n往鍊金釜隨意放置三個種子來釀造一瓶隨機藥劑! 每類種子都有著與之對應的藥劑。釀造的藥劑可能與原料種子相關，但也可能完全隨機。 使用更多相同種類的種子能夠減少出現隨機藥劑的機率。
journal.document.alchemy_guide.stones.title=鍛造符石
journal.document.alchemy_guide.stones.body=在鍊金釜中放入一張卷軸，就能使卷軸的魔力注入到兩塊石頭中。 就能鍛造出符石，你也能得知卷軸上文字的意思!
journal.document.alchemy_guide.energy_food.title=鍊金能量與食物烹飪
journal.document.alchemy_guide.energy_food.body=大多配方需要消耗鍊金能量。這些能量能從消耗品中提煉出來。與此同時也會鑑定提煉物。\n\n然而並非所有耗能配方都是神秘且不可告人的。 下面的這些配方比起鍊金更接近傳統烹飪法。
journal.document.alchemy_guide.exotic_potions.title=釀造合劑
journal.document.alchemy_guide.exotic_potions.body=將藥劑與一些煉金能量混合能製造合劑。他們有著比普通藥劑更酷的功能，但通常效果也有所差異。
journal.document.alchemy_guide.exotic_scrolls.title=合成秘卷
journal.document.alchemy_guide.exotic_scrolls.body=跟合劑一樣，秘卷也能以相同方式製成。它們的效果更顯著，但需要的能量也更多。
journal.document.alchemy_guide.bombs.title=改造炸彈
journal.document.alchemy_guide.bombs.body=一顆普通的炸彈可以與一個特定的物品共煉來製作強化炸彈。
journal.document.alchemy_guide.weapons.title=武器回收
journal.document.alchemy_guide.weapons.body=一些較輕的武器或魔法武器也能用在煉金術中!\n\n每一組投擲武器都能提煉成足以修復另一組相同等級及階級的投擲武器的液態金屬。即便它有被損耗!\n\n一支法杖則能夠產生足以升級兩支相同等級的法杖的奧術樹脂，但沒辦法超過+3。
journal.document.alchemy_guide.brews_elixirs.title=煉製魔藥與秘藥
journal.document.alchemy_guide.brews_elixirs.body=魔藥與秘藥是具有複雜效果的消耗品，產量通常只有一個。
journal.document.alchemy_guide.spells.title=提取法術
journal.document.alchemy_guide.spells.body=將物品能量封裝於結晶中以形成法術，它們具有不同用途的各類效果，大多種類的結晶在使用多次後才會失效。

journal.document.intros.title=地區簡介
journal.document.intros.discover_hint=首次進入特定區域即會解鎖此文本。
journal.document.intros.dungeon.title=地下城本體
journal.document.intros.sewers.title=下水道
journal.document.intros.prison.title=監獄
journal.document.intros.caves.title=洞穴
journal.document.intros.city.title=矮人都城
journal.document.intros.halls.title=惡魔大廳
journal.document.intros.halls.discover_hint=這些文本會在特定區域出現，但你得先蒐集這組紀錄之前的文本。

journal.document.sewers_guard.title=巡邏隊員的信件
journal.document.sewers_guard.discover_hint=這些文本會在特定區域出現，但你得先蒐集這組紀錄之前的文本。

journal.document.prison_warden.title=典獄長筆錄
journal.document.prison_warden.discover_hint=這些文本會在特定區域出現，但你得先蒐集這組紀錄之前的文本。

journal.document.caves_explorer.title=探險者的報告
journal.document.caves_explorer.discover_hint=這些文本會在特定區域出現，但你得先蒐集這組紀錄之前的文本。

journal.document.city_warlock.title=矮人術士手記
journal.document.city_warlock.discover_hint=這些文本會在特定區域出現，但你得先蒐集這組紀錄之前的文本。

journal.document.halls_king.title=???傳
journal.document.halls_king.discover_hint=這些文本會在特定區域出現，但你得先蒐集這組紀錄之前的文本。

journal.notes$landmark.shop=商店
journal.notes$landmark.alchemy=鍊金釜
journal.notes$landmark.garden=靜謐花圃
journal.notes$landmark.distant_well=遠處的井
journal.notes$landmark.well_of_health=生命之泉
journal.notes$landmark.well_of_awareness=覺察之泉
journal.notes$landmark.sacrificial_fire=獻祭烈焰
journal.notes$landmark.statue=活化石像
journal.notes$landmark.ghost=悲傷幽靈
journal.notes$landmark.rat_king=鼠王
journal.notes$landmark.wandmaker=老杖匠
journal.notes$landmark.troll=巨魔鐵匠
journal.notes$landmark.imp=野心勃勃的小惡魔
journal.notes$landmark.demon_spawner=惡魔血巢
